---
version: 2
multicolumn: false
web-width: 500
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/dots/dots.html
    type: html
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/237440/articles/308085/master/file/figures/dots/dots.html"
    folder_url: "/users/237440/articles/308085/master/folder/figures/dots"
